# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 20

[[main]]
  name = "CV"
  url = "files/cv.pdf"
  weight = 30

[[main]]
  name = "Publications"
  url = "#featured"
  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "Media Coverage"
  url = "#media-coverage-critical-Reviews"
  weight = 60

[[main]]
  name = "Credits"
  url = "#credits"
  weight = 70

[[main]]
  name = "Blog"
  url = "http://www.christopherodom.com/Blog"
  weight = 80

[[main]]
  name = "Invite Me"
  url = "#invite-me"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
